// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DB_enum.proto

#include "DB_enum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace protocol {
namespace db {
}  // namespace db
}  // namespace protocol
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_DB_5fenum_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_DB_5fenum_2eproto = nullptr;
const uint32_t TableStruct_DB_5fenum_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_DB_5fenum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rDB_enum.proto\022\013protocol.db*\026\n\nE_Packet"
  "ID\022\010\n\004TEST\020\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_DB_5fenum_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_DB_5fenum_2eproto = {
    false, false, 60, descriptor_table_protodef_DB_5fenum_2eproto,
    "DB_enum.proto",
    &descriptor_table_DB_5fenum_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_DB_5fenum_2eproto::offsets,
    nullptr, file_level_enum_descriptors_DB_5fenum_2eproto,
    file_level_service_descriptors_DB_5fenum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_DB_5fenum_2eproto_getter() {
  return &descriptor_table_DB_5fenum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_DB_5fenum_2eproto(&descriptor_table_DB_5fenum_2eproto);
namespace protocol {
namespace db {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* E_PacketID_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_DB_5fenum_2eproto);
  return file_level_enum_descriptors_DB_5fenum_2eproto[0];
}
bool E_PacketID_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace db
}  // namespace protocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
